import DropdownExample from '@/modules/landing/home/DropdownExample'

export * from './Layout'
export * from './icons'
export { default as OpenGraph } from './OpenGraph'
export { default as BannerDashboard } from '../modules/landing/home/BannerDashboard/BannerDashboard'
export { default as WindowEditor } from './WindowEditor'
export { default as TestimonialsBanner } from '../modules/landing/home/TestimonialsBanner'
export { default as ShowMore } from './ShowMore'
export { default as Badge } from './Badge'
export { default as CustomTableDocs } from './CustomTableDocs'
export { default as ContainerComponentDoc } from './ContainerComponentDoc'
export { default as CustomSwitch } from './CustomSwitch'
