on:
    push:
        branches:
            - main
    pull_request:
        branches: ['main']

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: npm
            - run: npm install

            - name: Build application
              run: npm run build
