name: SonarCloud analysis

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=dd3tech_dd360-components-docs
            -Dsonar.organization=dd3tech-1
