name: SonarCloud analysis

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
        with:
          args: >
            -Dsonar.projectKey=dd3tech_dd360-components-docs
            -Dsonar.organization=dd3tech-1 -Dsonar.java.jdkHome=$JAVA_HOME
